Feature/sync med origin
fredrikhgrelland/terraform-nomad-postgres pull request #23
Opened 2020-09-30 12:25 UTC by dangernil

Sync with master

2020-10-01 05:53 UTC, claesgill approved these changes
Ser bra ut for min del. Har kjørt opp og ser at postgres fungerer som forventet med `psql`.

2020-10-01 06:10 UTC, claesgill commented on LICENSE
> +=======
```suggestion
=======
```

2020-10-01 06:11 UTC, claesgill commented on LICENSE
> +=======
```suggestion
```

2020-10-01 06:11 UTC, claesgill commented on LICENSE
> +   limitations under the License.
```suggestion
```

2020-10-01 06:11 UTC, claesgill commented on Makefile
> +=======
```suggestion
```

2020-10-01 06:13 UTC, claesgill commented on README.md
> +=======
Ser det er en del `=======` i noen av filene. Ville gått gjennom å sjekket alle filene og fjernet disse.

2020-10-01 06:13 UTC, claesgill requested changes
Ser det er en del `=======` i noen av filene. Ville gått gjennom å sjekket alle filene og fjernet disse. Det er sikkert lettest å gjøre med søkefunksjon i Intellij :)

2020-10-01 06:50 UTC, zhenik requested changes

2020-10-01 06:50 UTC, zhenik commented on CHANGELOG.md
> +- links in documentation #5
I think this part is taken from the original template. Check existing [CHANGELOG.md](https://github.com/fredrikhgrelland/terraform-nomad-postgres/blob/master/CHANGELOG.md)

```suggestion
```

2020-10-01 06:50 UTC, zhenik commented on LICENSE
> +
```suggestion
```

2020-10-01 06:50 UTC, zhenik commented on Makefile
> +
```suggestion
```

2020-10-01 06:50 UTC, zhenik commented on Makefile
> +
```suggestion
update-box:
	@SSL_CERT_FILE=${SSL_CERT_FILE} CURL_CA_BUNDLE=${CURL_CA_BUNDLE} vagrant box update || (echo '\n\nIf you get an SSL error you might be behind a transparent proxy. \nMore info https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/README.md#proxy\n\n' && exit 2)

```

2020-10-01 06:50 UTC, zhenik commented on README.md
> +
```suggestion
```

2020-10-01 06:50 UTC, zhenik commented on README.md
@dangernil I think the whole README.md file is wrong. It supposed to describe postgres module, not template

2020-10-01 06:50 UTC, zhenik commented on README_template.md
> +<!-- markdownlint-disable MD041 -->
You need to move all content from `README_template.md` to `README.md` and vice versa

2020-10-01 06:50 UTC, zhenik commented on dev/ansible/README.md
> +Se [example](../../test_example/dev/ansible)
Broken link
```suggestion
```

2020-10-01 06:50 UTC, zhenik commented on dev/vagrant/conf/consul/README.md
>  See [example](../../../../test_example/dev/vagrant/conf/consul/99-override.hcl)
```suggestion
```

2020-10-01 06:50 UTC, zhenik commented on dev/vagrant/conf/nomad/README.md
> +See [example](../../../../test_example/dev/vagrant/conf/nomad/99-override.hcl)
Directory was renamed from `test_example` to `template_example`
```suggestion
```

2020-10-01 06:50 UTC, zhenik commented on dev/vagrant/conf/pre_bootstrap/README.md
> +See [example](../../../../test_example/dev/vagrant/conf/pre_bootstrap/00-prestart-example.yml)
```suggestion
```

2020-10-01 06:50 UTC, zhenik commented on dev/vagrant/conf/vault/README.md
> +See [example](../../../../test_example/dev/vagrant/conf/vault/99-override.hcl)
```suggestion
```

2020-10-01 12:48 UTC, Neha-Sinha2305 requested changes

2020-10-01 12:48 UTC, Neha-Sinha2305 commented on .github/action/create-env.py
> +filepath
```suggestion
filepath
```
We need to remove this from vagrant-hashistack code as well.

2020-10-01 12:55 UTC, Neha-Sinha2305 requested changes

2020-10-01 12:55 UTC, Neha-Sinha2305 commented on Vagrantfile
> +load default_vagrantfile if File.exists?(default_vagrantfile)
This file is not in order..it should just have the last two lines 13,14. Rest should be removed.
https://github.com/fredrikhgrelland/terraform-nomad-minio/blob/master/Vagrantfile

2020-10-02 08:42 UTC, zhenik requested changes

2020-10-02 08:42 UTC, zhenik commented on README.md
> -
Why you have removed this part?

2020-10-02 08:42 UTC, zhenik commented on .github/action/create-env.py
>      text_file.write(out_file)
```suggestion
```

2020-10-02 10:25 UTC, dangernil commented on README.md
> -
I agree, adding it back in

2020-10-02 11:23 UTC, zhenik approved these changes
LGTM

2020-10-02 11:43 UTC, merged